local camera = require "orthographic.camera"
local cursor = require "in.cursor"

function init(self)
	msg.post(".", "acquire_input_focus")

	self.url_robot1 = msg.url(nil, "/robot1", "robotController")
	self.url_robot2 = msg.url(nil, "/robot2", "robotController")
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("swap_url") then
		self.url_robot1, self.url_robot2 = self.url_robot2, self.url_robot1
	elseif message_id == cursor.CLICKED then
		if message.id == hash("/speed") then
			msg.post(self.url_robot1, "add_speed")

		elseif message.id == hash("/text_done") then
			msg.post("/game_controller#gameController", "text_done")

		elseif message.id == hash("/visual_done") then
			msg.post("/game_controller#gameController", "visual_done")

		elseif message.id == hash("/start_other_turn") then
			msg.post("/game_controller#gameController", "start_other_turn")

		elseif message.id == hash("/fight") then
			msg.post("/game_controller#gameController", "fight")

		elseif message.id == hash("/shield") then
			msg.post(self.url_robot1, "add_shield")

		elseif message.id == hash("/weapon_left") then
			msg.post(self.url_robot1, "add_weapon_left")

		elseif message.id == hash("/weapon_right") then
			msg.post(self.url_robot1, "add_weapon_right")

		elseif message.id == hash("/vector_up") then
			msg.post(self.url_robot1, "up_move_vector")

		elseif message.id == hash("/vector_down") then
			msg.post(self.url_robot1, "down_move_vector")

		elseif message.id == hash("/shield_up_down/up") then
			msg.post(msg.url(nil, "/shield_up_down/script", "buttonController"), "up")
			msg.post(self.url_robot2, "add_shield", {value = msg.url(nil, "/shield_up_down/script", "buttonController")})

		elseif message.id == hash("/shield_up_down/down") then
			msg.post(msg.url(nil, "/shield_up_down/script", "buttonController"), "down")
			msg.post(self.url_robot2, "add_shield", {value = msg.url(nil, "/shield_up_down/script", "buttonController")})

		elseif message.id == hash("/speed_up_down/up") then
			msg.post(msg.url(nil, "/speed_up_down/script", "buttonController"), "up")

		elseif message.id == hash("/speed_up_down/down") then
			msg.post(msg.url(nil, "/speed_up_down/script", "buttonController"), "down")

		elseif message.id == hash("/weapon_left_up_down/up") then
			msg.post(msg.url(nil, "/weapon_left_up_down/script", "buttonController"), "up")

		elseif message.id == hash("/weapon_left_up_down/down") then
			msg.post(msg.url(nil, "/weapon_left_up_down/script", "buttonController"), "down")

		elseif message.id == hash("/weapon_right_up_down/up") then
			msg.post(msg.url(nil, "/weapon_right_up_down/script", "buttonController"), "up")

		elseif message.id == hash("/weapon_right_up_down/down") then
			msg.post(msg.url(nil, "/weapon_right_up_down/script", "buttonController"), "down")

		elseif message.id == hash("/shield_text") then
			msg.post(self.url_robot2, "add_shield", {value = msg.url(nil, "/shield_up_down/script", "buttonController")})

		elseif message.id == hash("/speed_text") then
			msg.post(self.url_robot2, "add_speed", {value = msg.url(nil, "/speed_up_down/script", "buttonController")})

		elseif message.id == hash("/weapon_left_text") then
			msg.post(self.url_robot2, "add_weapon_left", {value = msg.url(nil, "/weapon_left_up_down/script", "buttonController")})

		elseif message.id == hash("/weapon_right_text") then
			msg.post(self.url_robot2, "add_weapon_right", {value = msg.url(nil, "/weapon_right_up_down/script", "buttonController")})

		elseif message.id == hash("/alig_up") then
			msg.post(self.url_robot2, "down_move_vector")

		elseif message.id == hash("/alig_down") then
			msg.post(self.url_robot2, "up_move_vector")

		elseif message.id == hash("/won_state") then
			msg.post("/game_controller#gameController", "build_state")
		end
	end
end

local CAMERA_ID = hash("/camera")
function on_input(self, action_id, action)
		local screen = vmath.vector3(action.x, action.y, 0)
	local world = camera.screen_to_world(CAMERA_ID, screen)
	action.x = world.x
	action.y = world.y
	msg.post("#cursor", "input", { action_id = action_id, action = action })
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
